title: Simple Linux Utility for Resource Management (SLURM)
subtitle: EDUCADO-MWGaiaDN Training School on Astro-AI and Machine Learning
author: Bernd Doser
date: 2026/03/05
date-format: "MMMM D, YYYY"
place: Ghent, Belgium
institute: Heidelberg Institute for Theoretical Studies (HITS)
format:
  revealjs:
    logo: images/HITS_RGB_eng.jpg
    footer: "EDUCADO: SLURM (B. Doser)"
    slide-number: true
    highlight-style: a11y
    bibliography: references.bib
    width: 1300
    menu: false
    show-slide-number: print