title: Simple Linux Utility for Resource Management (SLURM)
subtitle: EDUCADO-MWGaiaDN Training School on Astro-AI and Machine Learning
author: Bernd Doser
date: 2026/03/05
date-format: "MMMM D, YYYY"
place: Ghent, Belgium
institute: Heidelberg Institute for Theoretical Studies (HITS)
title-slide-attributes:
  data-background-image: images/jupyter.jpg
  data-background-size: cover
  data-background-opacity: "0.8"
format:
  revealjs:
    logo: images/HITS_RGB_eng.jpg
    footer: "EDUCADO: SLURM (B. Doser)"
    slide-number: true
    highlight-style: a11y
    code-line-numbers: false
    bibliography: references.bib
    width: 1300
    menu: false
    # show-slide-number: print
    css: styles.css
    font-size: 30px
